project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Graham Lewis"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: About
      - research.qmd
      - cv.qmd
      - teaching.qmd
      - href: agentic_ide.qmd
        text: Agentic IDE
  page-navigation: true
  
format:
  html:
    theme: [yeti, styles.scss]
    css: styles.css
    toc: false
    linkcolor: "#7a0117"
    anchor-sections: false

editor: visual




