project:
  type: website

website:
  title: "Graham Lewis"
  search: false
  navbar:
    right:
      # - href: index.qmd
        # text: About
      - research.qmd
      - teaching.qmd
  page-navigation: true
  
format:
  html:
    theme: [yeti, styles.scss]
    css: styles.css
    toc: false
    linkcolor: "#7a0117"
    anchor-sections: false

editor: visual

