---
title: "Teaching"
format: 
  html:
    includes:
      in_header: "style.css"
    css: about.css
---

<!-- Horizontal line between course blocks -->

<hr>

:::::: course-block
::: course-title
ECON 3023: Intermediate Macroeconomics
:::

::: course-info
**Semester:** Summer 2025\
**Instructor:** Graham Lewis
:::

<p class="course-description">

Determinants of national income, employment, and price level; effects of monetary and fiscal policies; emphasis on a general equilibrium approach.

</p>

::: course-materials
<details>

<summary><strong>Lecture Slides</strong></summary>

-   [Lecture 1 - Introduction](lectures/lecture1_Introduction.pdf){target="_blank"}
-   [Lecture 2 - Production](lectures/lecture2_Production.pdf){target="_blank"}
-   [Lecture 3 - Solow](lectures/lecture3_Solow.pdf){target="_blank"}
-   [Lecture 4 - Ideas](lectures/lecture4_Ideas.pdf){target="_blank"}
-   [Lecture 5 - Beyond Physical Capital](lectures/lecture5_expandingCapital.pdf){target="_blank"}
-   [Lecture 6 - Human Capital](lectures/lecture6_HumanCapital.pdf){target="_blank"}
-   [Lecture 7 - Unmeasured Capital](lectures/lecture7_UnmeasuredCapital.pdf){target="_blank"}
-   [Lecture 8 - Labor Supply](lectures/lecture8_LaborSupply.pdf){target="_blank"}
-   [Lecture 9 - Taxes](lectures/lecture9_Taxes.pdf){target="_blank"}
-   [Lecture 10 - Transfers](lectures/lecture10_Transfers.pdf){target="_blank"}

</details>

<details>

<summary><strong>Homework Assignments️</strong></summary>

- [HW 1 – Production and Solow](homeworks/hw1.pdf){target="_blank"}
- [HW 2 – Romer and Human Capital](homeworks/hw2.pdf){target="_blank"}
- [HW 3 – Unmeasured Capital and Labor Supply](homeworks/hw3.pdf){target="_blank"}

</details>
:::
::::::

<hr>

## Teaching Assistant

:::::: course-block
::: course-title
ECON 3023, 3024: Intermediate Macroeconomics
:::

::: course-info
Semester: Spring 2025, Fall 2024
:::

::: course-info
University of Minnesota (Head TA)
:::

<p class="course-description">

Determinants of national income, employment, and price level; effects of monetary and fiscal policies; emphasis on a general equilibrium approach.

</p>
::::::

<hr>

:::::: course-block
::: course-title
ECON 3011, 3012: Intermediate Microeconomics
:::

::: course-info
Semester: Fall 2024, Summer 2024
:::

::: course-info
University of Minnesota (TA)
:::

<p class="course-description">

Behavior of households, firms, and industries under competitive/monopolistic conditions.

</p>
::::::

<hr>

<!-- Horizontal line between course blocks -->

:::::: course-block
::: course-title
ECON 1102: Principles of Macroeconomics
:::

::: course-info
Semester: Spring 2024
:::

::: course-info
University of Minnesota (TA)
:::

<p class="course-description">

Aggregate consumption, saving, investment, and national income. Role of money, banking, and business cycles in domestic and world economy.

</p>
::::::

<hr>

:::::: course-block
::: course-title
ECON 1101: Principles of Microeconomics
:::

::: course-info
Semester: Fall 2023
:::

::: course-info
University of Minnesota (TA)
:::

<p class="course-description">

Microeconomic behavior of consumers, firms, and markets in domestic and world economy

</p>
::::::

<hr>

:::::: course-block
::: course-title
MATH 2552: Differential Equations
:::

::: course-info
Semester: Fall 2022
:::

::: course-info
Georgia Tech (TA)
:::

<p class="course-description">

Methods for obtaining numerical and analytic solutions of elementary differential equations. Applications are also discussed with an emphasis on modeling.

</p>
::::::

<hr>

:::::: course-block
::: course-title
MATH 2550: Introduction to Multivariable Calculus
:::

::: course-info
Semester: Spring 2022
:::

::: course-info
Georgia Tech (TA)
:::

<p class="course-description">

An introduction to multivariable calculus through vectors in 3D, curves, functions of several variables, partial derivatives, min/max problems, multiple integration.

</p>
::::::

<hr>
